# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=30)),
                ('businessEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourOccupantsCount', models.IntegerField()),
                ('userF', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policeStationName', models.CharField(max_length=30)),
                ('policeEmergencyNbr', models.IntegerField()),
                ('neighbourF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourapp.Neighbour')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(default='default.jpg', upload_to='profileImg/')),
                ('neighbourName', models.CharField(max_length=30)),
                ('neighbourLocation', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='neighbourF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourapp.Neighbour'),
        ),
    ]
