# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourLocation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourName',
        ),
    ]
