# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0002_auto_20191101_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbour',
            name='neighbourLocation',
            field=models.CharField(choices=[('Gasabo', 'Gasabo'), ('Nyarugenge', 'Nyarugenge'), ('Kicukiro', 'Kicukiro')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbour',
            name='neighbourName',
            field=models.CharField(choices=[('Kimironko', 'Kimironko'), ('Nyamirambo', 'Nyamirambo'), ('Rebero', 'Rebero')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
