# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0004_remove_neighbour_neighbouroccupantscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbour',
            old_name='userF',
            new_name='user',
        ),
    ]
