# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0005_auto_20191101_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbour',
            name='neighbourLocation',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='neighbour',
            name='neighbourName',
            field=models.CharField(max_length=60),
        ),
    ]
