# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0006_auto_20191101_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourLocation',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourName',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
