# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0007_auto_20191101_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourLocation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourName',
        ),
        migrations.AlterField(
            model_name='neighbour',
            name='neighbourLocation',
            field=models.CharField(choices=[('Gasabo', 'Gasabo'), ('Nyarugenge', 'Nyarugenge'), ('Kicukiro', 'Kicukiro')], max_length=60),
        ),
        migrations.AlterField(
            model_name='neighbour',
            name='neighbourName',
            field=models.CharField(choices=[('Kimironko', 'Kimironko'), ('Nyamirambo', 'Nyamirambo'), ('Rebero', 'Rebero')], max_length=60),
        ),
    ]
