# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0011_auto_20191105_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='businessImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='business/'),
            preserve_default=False,
        ),
    ]
