# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0012_business_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(default='default.jpg', upload_to='post/'),
        ),
    ]
