# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0015_police_policeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postNeighbourName',
            field=models.CharField(choices=[('Amahoro', 'Amahoro'), ('Agaciro', 'Agaciro'), ('Intsinzi', 'Intsinzi')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
